<?php
return array (
  3 => 
  array (
    'id' => '3',
    'catid' => '17',
    'typeid' => '0',
    'title' => 'c入门教程',
    'style' => '',
    'thumb' => '',
    'keywords' => '入门教程',
    'description' => '点点滴滴',
    'posids' => '0',
    'url' => 'http://127.0.0.10/index.php?m=content&c=index&a=show&catid=17&id=3',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'it915',
    'inputtime' => '1405425450',
    'updatetime' => '1405477354',
    'hitsid' => 'c-1-3',
    'views' => '6',
    'yesterdayviews' => '0',
    'dayviews' => '6',
    'weekviews' => '6',
    'monthviews' => '6',
  ),
  4 => 
  array (
    'id' => '4',
    'catid' => '17',
    'typeid' => '0',
    'title' => '阿三地方',
    'style' => '',
    'thumb' => '',
    'keywords' => '地方',
    'description' => 'a  d  f',
    'posids' => '0',
    'url' => 'http://127.0.0.10/index.php?m=content&c=index&a=show&catid=17&id=4',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'admin',
    'inputtime' => '1405490332',
    'updatetime' => '1405490341',
    'hitsid' => 'c-1-4',
    'views' => '0',
    'yesterdayviews' => '0',
    'dayviews' => '0',
    'weekviews' => '0',
    'monthviews' => '0',
  ),
  5 => 
  array (
    'id' => '5',
    'catid' => '17',
    'typeid' => '0',
    'title' => 'ffff',
    'style' => '',
    'thumb' => '',
    'keywords' => 'ff',
    'description' => 'ff',
    'posids' => '0',
    'url' => 'http://127.0.0.10/index.php?m=content&c=index&a=show&catid=17&id=5',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'admin',
    'inputtime' => '1405667601',
    'updatetime' => '1405667623',
    'hitsid' => 'c-1-5',
    'views' => '0',
    'yesterdayviews' => '0',
    'dayviews' => '0',
    'weekviews' => '0',
    'monthviews' => '0',
  ),
);
?>