<?php
return array (
  1 => 
  array (
    'id' => '1',
    'catid' => '18',
    'typeid' => '0',
    'title' => 'ddd',
    'style' => '',
    'thumb' => '',
    'keywords' => 'dd',
    'description' => 'dddd',
    'posids' => '0',
    'url' => 'http://127.0.0.10//xiazai/20140710/1.html',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'it915',
    'inputtime' => '1404999020',
    'updatetime' => '1404999106',
    'hitsid' => 'c-1-1',
    'views' => '2',
    'yesterdayviews' => '0',
    'dayviews' => '2',
    'weekviews' => '2',
    'monthviews' => '2',
  ),
  4 => 
  array (
    'id' => '4',
    'catid' => '17',
    'typeid' => '0',
    'title' => 'mysql5.5版本主从数据库同步详解',
    'style' => '',
    'thumb' => '',
    'keywords' => 'dddd',
    'description' => '以前做mysql主从同步，以前用mysql5 1直接配置2个my ini配置文件就可以，比较方便，最近用Mysql5 5，按照那种方法，配置完以 后，重启mysql服务器，启动不了，查询了手册，才知道mysql5 5 版本以上',
    'posids' => '0',
    'url' => 'http://127.0.0.10/index.php?m=content&c=index&a=show&catid=17&id=4',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'it915',
    'inputtime' => '1405427556',
    'updatetime' => '1405427562',
    'hitsid' => 'c-1-4',
    'views' => '0',
    'yesterdayviews' => '0',
    'dayviews' => '0',
    'weekviews' => '0',
    'monthviews' => '0',
  ),
  5 => 
  array (
    'id' => '5',
    'catid' => '19',
    'typeid' => '0',
    'title' => 'fdg',
    'style' => '',
    'thumb' => '',
    'keywords' => 'sdfg',
    'description' => 'sdfgsdfg',
    'posids' => '0',
    'url' => 'http://127.0.0.10/c/tigao/20140715/5.html',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'it915',
    'inputtime' => '1405430424',
    'updatetime' => '1405430429',
    'hitsid' => 'c-1-5',
    'views' => '0',
    'yesterdayviews' => '0',
    'dayviews' => '0',
    'weekviews' => '0',
    'monthviews' => '0',
  ),
);
?>