<?php
return array (
  2 => 
  array (
    'id' => '2',
    'catid' => '10',
    'typeid' => '0',
    'title' => 'php 如何实现二位数组',
    'style' => '',
    'thumb' => '',
    'keywords' => 'dddd',
    'description' => '大幅',
    'posids' => '0',
    'url' => 'http://127.0.0.10/php/rumen/20140713/2.html',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'it915',
    'inputtime' => '1405258086',
    'updatetime' => '1405489474',
    'hitsid' => 'c-1-2',
    'views' => '7',
    'yesterdayviews' => '0',
    'dayviews' => '7',
    'weekviews' => '7',
    'monthviews' => '7',
  ),
  6 => 
  array (
    'id' => '6',
    'catid' => '26',
    'typeid' => '0',
    'title' => 'php学习必须具备的要素',
    'style' => '',
    'thumb' => '',
    'keywords' => '要素',
    'description' => 'php学习',
    'posids' => '0',
    'url' => 'http://127.0.0.10/php/rumen/rumen_2/20140721/6.html',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'admin',
    'inputtime' => '1405912781',
    'updatetime' => '1405912811',
    'hitsid' => 'c-1-6',
    'views' => '0',
    'yesterdayviews' => '0',
    'dayviews' => '0',
    'weekviews' => '0',
    'monthviews' => '0',
  ),
  7 => 
  array (
    'id' => '7',
    'catid' => '26',
    'typeid' => '0',
    'title' => 'php学习必须知道的内容',
    'style' => '',
    'thumb' => '',
    'keywords' => '内容',
    'description' => '啊手动阀手动阀',
    'posids' => '0',
    'url' => 'http://127.0.0.10/php/rumen/rumen_2/20140721/7.html',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'admin',
    'inputtime' => '1405920233',
    'updatetime' => '1405920265',
    'hitsid' => 'c-1-7',
    'views' => '0',
    'yesterdayviews' => '0',
    'dayviews' => '0',
    'weekviews' => '0',
    'monthviews' => '0',
  ),
  8 => 
  array (
    'id' => '8',
    'catid' => '27',
    'typeid' => '0',
    'title' => 'lamp环境搭建教程',
    'style' => '',
    'thumb' => '',
    'keywords' => '环境 教程',
    'description' => 'lamp环境搭建教程',
    'posids' => '0',
    'url' => 'http://127.0.0.10/php/rumen/rumen_2/20140721/8.html',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'admin',
    'inputtime' => '1405929496',
    'updatetime' => '1405929524',
    'hitsid' => 'c-1-8',
    'views' => '0',
    'yesterdayviews' => '0',
    'dayviews' => '0',
    'weekviews' => '0',
    'monthviews' => '0',
  ),
);
?>