<?php
return array (
  4 => 
  array (
    'id' => '4',
    'catid' => '17',
    'typeid' => '0',
    'title' => '阿三地方',
    'style' => '',
    'thumb' => '',
    'keywords' => '地方',
    'description' => 'a  d  f',
    'posids' => '0',
    'url' => 'http://127.0.0.10/c/rumen/20140716/4.html',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'admin',
    'inputtime' => '1405490332',
    'updatetime' => '1406101045',
    'hitsid' => 'c-1-4',
    'views' => '9',
    'yesterdayviews' => '2',
    'dayviews' => '7',
    'weekviews' => '9',
    'monthviews' => '9',
  ),
  3 => 
  array (
    'id' => '3',
    'catid' => '17',
    'typeid' => '0',
    'title' => 'c入门教程',
    'style' => '',
    'thumb' => '',
    'keywords' => '入门教程',
    'description' => '点点滴滴',
    'posids' => '0',
    'url' => 'http://127.0.0.10/c/rumen/20140715/3.html',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'it915',
    'inputtime' => '1405425450',
    'updatetime' => '1406078267',
    'hitsid' => 'c-1-3',
    'views' => '8',
    'yesterdayviews' => '1',
    'dayviews' => '1',
    'weekviews' => '2',
    'monthviews' => '8',
  ),
  5 => 
  array (
    'id' => '5',
    'catid' => '17',
    'typeid' => '0',
    'title' => 'ffff',
    'style' => '',
    'thumb' => '',
    'keywords' => 'ff',
    'description' => 'ff',
    'posids' => '0',
    'url' => 'http://127.0.0.10/c/rumen/20140718/5.html',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'admin',
    'inputtime' => '1405667601',
    'updatetime' => '1405998302',
    'hitsid' => 'c-1-5',
    'views' => '7',
    'yesterdayviews' => '0',
    'dayviews' => '7',
    'weekviews' => '7',
    'monthviews' => '7',
  ),
);
?>