<?php
return array (
  8 => 
  array (
    'id' => '8',
    'catid' => '27',
    'typeid' => '0',
    'title' => 'lamp环境搭建教程',
    'style' => '',
    'thumb' => '',
    'keywords' => '环境 教程',
    'description' => 'lamp环境搭建教程',
    'posids' => '0',
    'url' => 'http://127.0.0.10/php/rumen/rumen_2/20140721/8.html',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'admin',
    'inputtime' => '1405929496',
    'updatetime' => '1406016746',
    'hitsid' => 'c-1-8',
    'views' => '14',
    'yesterdayviews' => '0',
    'dayviews' => '14',
    'weekviews' => '14',
    'monthviews' => '14',
  ),
  6 => 
  array (
    'id' => '6',
    'catid' => '26',
    'typeid' => '0',
    'title' => 'php学习必须具备的要素',
    'style' => '',
    'thumb' => '',
    'keywords' => '要素',
    'description' => 'php学习',
    'posids' => '0',
    'url' => 'http://127.0.0.10/php/rumen/rumen_2/20140721/6.html',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'admin',
    'inputtime' => '1405912781',
    'updatetime' => '1406008795',
    'hitsid' => 'c-1-6',
    'views' => '9',
    'yesterdayviews' => '0',
    'dayviews' => '9',
    'weekviews' => '9',
    'monthviews' => '9',
  ),
  7 => 
  array (
    'id' => '7',
    'catid' => '26',
    'typeid' => '0',
    'title' => 'php学习必须知道的内容',
    'style' => '',
    'thumb' => '',
    'keywords' => '内容',
    'description' => '啊手动阀手动阀',
    'posids' => '0',
    'url' => 'http://127.0.0.10/php/rumen/rumen_2/20140721/7.html',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'admin',
    'inputtime' => '1405920233',
    'updatetime' => '1406008780',
    'hitsid' => 'c-1-7',
    'views' => '4',
    'yesterdayviews' => '0',
    'dayviews' => '4',
    'weekviews' => '4',
    'monthviews' => '4',
  ),
);
?>